### PR TITLE
Move alternative builds to 18.04

### PR DESCRIPTION
**Pull request by giorgiosironi**
From https://github.com/elifesciences/issues/issues/4780

Depends on:
* https://github.com/elifesciences/builder/pull/468
* https://github.com/elifesciences/builder/pull/470

### CODE REVIEW

**Comment by giorgiosironi** [comment]
Had some problems in running on 18.04, but haven't looked into it. @lsh-0 this may be of interest, and probably your fixes will make it work more easily.

**Comment by lsh-0** [comment]
I'll take a look at this one today.

**Comment by lsh-0** [comment]
ok, those two checks failed because of the older version of salt being used, so this PR also depends on https://github.com/elifesciences/builder/pull/470

**Comment by lsh-0** [comment]
giving this build a kick. The two related issues have been sorted

**Comment by lsh-0** [comment]
```salt
[2019-12-16T01:42:20.966Z] ERROR - buildercore.cloudformation - unhandled exception attempting to create stack
[2019-12-16T01:42:20.966Z] Traceback (most recent call last):
[2019-12-16T01:42:20.966Z]   File "/ext/srv/builder/src/buildercore/cloudformation.py", line 64, in stack_creation
[2019-12-16T01:42:20.966Z]     on_start()
[2019-12-16T01:42:20.966Z]   File "/ext/srv/builder/src/buildercore/cloudformation.py", line 93, in <lambda>
[2019-12-16T01:42:20.966Z]     on_start = lambda: keypair.create_keypair(stackname)
[2019-12-16T01:42:20.966Z]   File "/ext/srv/builder/src/buildercore/keypair.py", line 67, in create_keypair
[2019-12-16T01:42:20.966Z]     expected_key = stack_pem(stackname, die_if_exists=True)
[2019-12-16T01:42:20.966Z]   File "/ext/srv/builder/src/buildercore/core.py", line 242, in stack_pem
[2019-12-16T01:42:20.966Z]     raise EnvironmentError("keypair %r found at %r, not overwriting." % (stackname, expected_key))
[2019-12-16T01:42:20.966Z] EnvironmentError: keypair 'elife-libraries--pr-11-fresh-s1804' found at '/ext/srv/builder/.cfn/keypairs/elife-libraries--pr-11-fresh-s1804.pem', not overwriting.
[2019-12-16T01:42:20.966Z] 2019-12-16 01:42:20,800 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2019-12-16T01:42:20.966Z] INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (1): ec2.us-east-1.amazonaws.com
[2019-12-16T01:42:21.216Z] INFO - buildercore.s3 - deleting key keypairs/elife-libraries--pr-11-fresh-s1804.pem
[2019-12-16T01:42:21.216Z] 2019-12-16 01:42:21,024 botocore.vendored.requests.packages.urllib3.connectionpool [INFO] Starting new HTTPS connection (3): elife-builder.s3.amazonaws.com
[2019-12-16T01:42:21.216Z] INFO - botocore.vendored.requests.packages.urllib3.connectionpool - Starting new HTTPS connection (3): elife-builder.s3.amazonaws.com
[2019-12-16T01:42:21.216Z] [localhost] local: ssh -o "StrictHostKeyChecking no" ubuntu@3.95.63.60 "exit"
[2019-12-16T01:42:21.216Z] True
[2019-12-16T01:42:21.216Z] exception while executing task 'masterless.launch': keypair 'elife-libraries--pr-11-fresh-s1804' found at '/ext/srv/builder/.cfn/keypairs/elife-libraries--pr-11-fresh-s1804.pem', not overwriting.
[2019-12-16T01:42:21.216Z] 
[2019-12-16T01:42:21.216Z] Traceback (most recent call last):
[2019-12-16T01:42:21.216Z]   File "src/taskrunner.py", line 215, in exec_task
[2019-12-16T01:42:21.216Z]     return_map['result'] = task_map['fn'](*task_args, **task_kwargs)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/decorators.py", line 42, in wrap2
[2019-12-16T01:42:21.216Z]     return func(pname, *args, **kwargs)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/masterless.py", line 20, in wrapper
[2019-12-16T01:42:21.216Z]     return fn(*args, **kwargs)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/masterless.py", line 101, in launch
[2019-12-16T01:42:21.216Z]     bootstrap.create_stack(stackname)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/bootstrap.py", line 74, in create_stack
[2019-12-16T01:42:21.216Z]     cloudformation.bootstrap(stackname, context)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/cloudformation.py", line 104, in bootstrap
[2019-12-16T01:42:21.216Z]     with stack_creation(stackname, on_start=on_start, on_error=on_error):
[2019-12-16T01:42:21.216Z]   File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
[2019-12-16T01:42:21.216Z]     return self.gen.next()
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/cloudformation.py", line 64, in stack_creation
[2019-12-16T01:42:21.216Z]     on_start()
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/cloudformation.py", line 93, in <lambda>
[2019-12-16T01:42:21.216Z]     on_start = lambda: keypair.create_keypair(stackname)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/keypair.py", line 67, in create_keypair
[2019-12-16T01:42:21.216Z]     expected_key = stack_pem(stackname, die_if_exists=True)
[2019-12-16T01:42:21.216Z]   File "/ext/srv/builder/src/buildercore/core.py", line 242, in stack_pem
[2019-12-16T01:42:21.216Z]     raise EnvironmentError("keypair %r found at %r, not overwriting." % (stackname, expected_key))
[2019-12-16T01:42:21.216Z] EnvironmentError: keypair 'elife-libraries--pr-11-fresh-s1804' found at '/ext/srv/builder/.cfn/keypairs/elife-libraries--pr-11-fresh-s1804.pem', not overwriting.
[2019-12-16T01:42:21.216Z]
```

**Comment by lsh-0** [comment]
don't know which machine that key is on to delete it. I'll open this as another PR

**Pull request closed without merging**
